### ISSUE TITLE
Missing support for rgb(r g b / a%) format

### ISSUE THREAD

**Issue by jonaskohl** [bbugh/vscode-change-color-format#65]
CSS Colors Level 4 adds support for space-separated values in the rgb color function: `rgb(R G B[ / A])`. This extension does not support this format yet, stating an "Unknown color format".

**Comment by bbugh** [comment]
Closing in favor of https://github.com/bbugh/vscode-change-color-format/issues/75

**Comment by bbugh** [comment]
Thanks for your interest @jonaskohl, feel free to PR for #75 if you're interested!
