### ISSUE TITLE
hsla is outdated

### ISSUE THREAD

**Issue by tomByrer** [bbugh/vscode-change-color-format#68]
> legacy hsla() syntax is an alias for hsl(), accepting the same parameters and behaving in the same way

Also accepts ['space & slash' delimitation](https://github.com/bbugh/vscode-change-color-format/issues/65#issue-1431160829).
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl

TIA :)

**Comment by bbugh** [comment]
Closing in favor of https://github.com/bbugh/vscode-change-color-format/issues/75

**Comment by bbugh** [comment]
Thanks for your interest @tomByrer, feel free to PR for #75 if you're interested!
