### ISSUE TITLE
can't see the covert command in vscode

### ISSUE THREAD

**Issue by guguji5** [bbugh/vscode-change-color-format#69]
I install the vscode plugin, but could not see the command. is there any shortcut command?

**Comment by bbugh** [comment]
Hi, it should appear in your command palette. I'm not doing anything special in the extension except registering the command with VSCode, so if you don't see it, I'm guessing it's not installed correctly.

<img width="593" alt="image" src="https://github.com/bbugh/vscode-change-color-format/assets/438465/058f7ea3-9225-43ce-bdfe-32f0ba969f1a">

**Comment by bbugh** [comment]
Thanks for your interest @guguji5, feel free to PR for #75 if you're interested!
